version: "3.4"

services:
    api:
        ports:
            - 8000:8000
        build:
            context: ./mzawadie-backend-django
            dockerfile: ./Dockerfile
            args:
                STATIC_URL: "/static/"
        restart: unless-stopped
        networks:
            - mzawadie-backend-tier
        stdin_open: true
        tty: true
        depends_on:
            - db
            - redis
            - jaeger
        volumes:
            - ./mzawadie-backend-django/mzawadie/:/app/mzawadie:Z
            - ./mzawadie-backend-django/templates/:/app/templates:Z
            - ./mzawadie-backend-django/tests/:/app/tests
            # shared volume between worker and api for media
            - mzawadie-media:/app/media
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - common.env
            - backend.env
        environment:
            - JAEGER_AGENT_HOST=jaeger
            - STOREFRONT_URL=http://localhost:3000/
            - DASHBOARD_URL=http://localhost:9000/
            - ALLOWED_HOSTS=localhost,api

    storefront:
        extends:
            file: ./mzawadie-storefront/docker-compose.yml
            service: storefront
        networks:
            - mzawadie-backend-tier
        depends_on:
            - api
            - mzawadie-app-checkout

    mzawadie-app-checkout:
        extends:
            file: ./mzawadie-storefront/docker-compose.yml
            service: mzawadie-app-checkout
        networks:
            - mzawadie-backend-tier
        depends_on:
            - api

    dashboard:
        build:
            context: ./mzawadie-dashboard-nextjs
            dockerfile: ./Dockerfile
        ports:
            - 9000:80
        restart: unless-stopped

    db:
        image: library/postgres:13-alpine
        ports:
            - 5432:5432
        restart: unless-stopped
        networks:
            - mzawadie-backend-tier
        volumes:
            - mzawadie-db:/var/lib/postgresql/data
            - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
        environment:
            - POSTGRES_USER=mzawadie
            - POSTGRES_PASSWORD=mzawadie

    redis:
        image: library/redis:5.0-alpine
        ports:
            - 6379:6379
        restart: unless-stopped
        networks:
            - mzawadie-backend-tier
        volumes:
            - mzawadie-redis:/data

    worker:
        build:
            context: ./mzawadie-backend-django
            dockerfile: ./Dockerfile
            args:
                STATIC_URL: "/static/"
        command: celery -A mzawadie --app=mzawadie.celeryconf:app worker --loglevel=info -B
        restart: unless-stopped
        networks:
            - mzawadie-backend-tier
        env_file:
            - common.env
            - backend.env
        depends_on:
            - redis
            - mailhog
        volumes:
            - ./mzawadie-backend-django/mzawadie/:/app/mzawadie:Z,cached
            - ./mzawadie-backend-django/templates/:/app/templates:Z,cached
            # shared volume between worker and api for media
            - mzawadie-media:/app/media

    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
        restart: unless-stopped
        networks:
            - mzawadie-backend-tier

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
        restart: unless-stopped
        networks:
            - mzawadie-backend-tier

volumes:
    mzawadie-db:
        driver: local
    mzawadie-redis:
        driver: local
    mzawadie-media:

networks:
    mzawadie-backend-tier:
        driver: bridge
